DATABASE_TYPE: FLAT # FLAT, MONGO
DATABASE:
  HOST: localhost
  PORT: 27017
  DATABASE: mteams
  AUTH:
    ENABLED: false
    USER: admin
    PASSWORD: ""
ONLINE_PREFIX: "&a"
OFFLINE_PREFIX: "&7"
CREATE_BROADCAST: true
DISBAND_BROADCAST: false
TEAMS_PER_PAGE:
  LIST: 10
  TOP: 10
TEAM_SIZE: 8
NAME_MIN_LENGTH: 3
NAME_MAX_LENGTH: 8
CHAT_PREFIX: "&8[&a%teamName%&8]&r "
INVITATION_EXPIRE: 30000 # in milliseconds (1000 milliseconds = 1 second)
